[package]
name = "rust-peal"
version = "0.1.0"
authors = ["Chris Jefferson <caj21@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "perm"
]

[dependencies]
perm = {version = "0.1.0", path = "perm" }