[package]
name = "rust-peal"
version = "0.1.0"
authors = ["Chris Jefferson <caj21@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "perm",
    "digraph",
    "partitionstack",
    "graphiso",
    "vole"
]

[dependencies]
perm = {version = "0.1.0", path = "perm" }
digraph = {version = "0.1.0", path = "digraph" }
partitionstack = {version = "0.1.0", path = "partitionstack" }
trace = {version = "0.1.0", path = "trace" }
graphiso = {version = "0.1.0", path = "graphiso" }
vole = {version = "0.1.0", path = "vole" }
log = "0.4.8"
