name: CI

# Trigger the workflow on push or pull request
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # Every day at 1:30 AM UTC
    - cron: '30 1 * * *'

jobs:
  # The CI test job
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11

    steps:
      - uses: actions/checkout@v2
      - name: "Set up rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build the rust component of Vole"
        run: cd rust && cargo build --release --all-features
      - name: "Run the rust tests for Vole"
        run: cd rust && cargo test --release -q
      - name: "Install GAP and the necessary packages"
        uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          GAP_PKGS_TO_CLONE: "datastructures ChrisJefferson/QuickCheck peal/BacktrackKit peal/GraphBacktracking"
          GAP_PKGS_TO_BUILD: "datastructures digraphs ferret io json orb profiling"
      - name: "Run GAP tests for Vole"
        uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v1
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15

  # The Cygwin job
  cygwin:
    name: Cygwin / GAP master
    runs-on: windows-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false

    #defaults:
    #  run:
    #    shell: C:\cygwin64\bin\bash.exe --login -o igncr '{0}'

    env:
      CHERE_INVOKING: 1

    steps:
      - uses: actions/checkout@v2
      - name: "Install Cygwin"
        uses: gap-actions/setup-cygwin@master
      - name: "Set up rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build the rust component of Vole"
        run: cd rust && cargo build --release --all-features
      - name: "Run the rust tests for Vole"
        run: cd rust && cargo test --release -q
      - name: "Install GAP and the necessary packages"
        uses: wilfwilson/setup-gap@cygwin
        with:
          GAP_PKGS_TO_CLONE: "datastructures ChrisJefferson/QuickCheck peal/BacktrackKit peal/GraphBacktracking"
          GAP_PKGS_TO_BUILD: "datastructures digraphs ferret io json orb profiling"
      - name: "Run GAP tests for Vole"
        uses: wilfwilson/run-pkg-tests@cygwin
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: ''
      - name: 'Add a necessary symlink'
        shell: bash
        run: |
          mkdir -p gaproot/pkg/
          ln -f -s $PWD gaproot/pkg/
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload PDF manual'
        uses: actions/upload-artifact@v2
        with:
          name: Vole manual (PDF)
          path: ./doc/manual.pdf
          retention-days: 3
      - name: 'Upload HTML manual'
        uses: actions/upload-artifact@v2
        with:
          name: Vole manual (HTML)
          path: |
            doc/*.html
            doc/*.css
            doc/*.js
          retention-days: 3
